/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AgentDashboard: () => import('#controllers/agent_dashboard_controller'),
  ConfirmOtps: () => import('#controllers/confirm_otps_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
