/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ReportPhotoSchema extends BaseModel {
  static $columns = ['createdAt', 'filePath', 'id', 'reportId'] as const
  $columns = ReportPhotoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare filePath: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reportId: number | null
}

export class ReportStatusHistorySchema extends BaseModel {
  static $columns = ['changedBy', 'comment', 'createdAt', 'id', 'newStatus', 'oldStatus', 'reportId'] as const
  $columns = ReportStatusHistorySchema.$columns
  @column()
  declare changedBy: number | null
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newStatus: string
  @column()
  declare oldStatus: string | null
  @column()
  declare reportId: number | null
}

export class ReportSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'description', 'id', 'latitude', 'longitude', 'status', 'title', 'updatedAt', 'userId'] as const
  $columns = ReportSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'isVerified', 'otp', 'otpExpiresAt', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean
  @column()
  declare otp: number | null
  @column.dateTime()
  declare otpExpiresAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
